#默认使用配置
spring:
  profiles:
    active: dev
  resources:
    static-locations: classpath:/static
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.xzh.clothes
  mapperLocations: classpath:mapper/*.xml

---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://120.79.85.238:3306/clothing?userUnicode=true&characterEncoding=utf8
    username: root
    password: Shen123..
    driver-class-name: com.mysql.jdbc.Driver
    ConnectionTestQuery: SELECT 1
    # 使用druid数据源

#  pagehelper.helper-dialect=MYSQL
#  3 pagehelper.reasonable=true
#  4 pagehelper.support-methods-arguments=true
#  5 pagehelper.params=count=countSql

pagehelper:
  helper-dialect: MYSQL
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
