#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.xzh.clothes
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://120.79.85.238:3306/clothing
    username: root
    password: Shen123..
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源